version: "3.9"
services:
  gateway:
    build: ./infra/docker/gateway
    ports: ["8080:8080"]
    env_file: .env
    depends_on: [orchestrator, qdrant, redis]

  orchestrator:
    build: ./infra/docker/orchestrator
    env_file: .env
    depends_on: [qdrant, redis]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes:
      - ./data/qdrant:/qdrant/storage

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]

  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
